### ISSUE TITLE
sitediff store ends up in ArgumentError

### ISSUE THREAD

**Issue by DanielSiepmann** [evolvingweb/sitediff#153]
Steps to reproduce:
```
docker run -p 13080:13080 -t -it --name sitediff --rm -v $(pwd):/project --workdir=/project evolvingweb/sitediff:latest /bin/bash
root@f80772921e74:/project# sitediff store
Reading config file: /project/sitediff/sitediff.yaml
/usr/local/bundle/gems/sitediff-1.2.3/lib/sitediff/fetch.rb:13:in `initialize': wrong number of arguments (given 6, expected 3..5) (ArgumentError)
        from /usr/local/bundle/gems/sitediff-1.2.3/lib/sitediff/api.rb:232:in `new'
        from /usr/local/bundle/gems/sitediff-1.2.3/lib/sitediff/api.rb:232:in `store'
        from /usr/local/bundle/gems/sitediff-1.2.3/lib/sitediff/cli.rb:221:in `store'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/sitediff-1.2.3/bin/sitediff:12:in `<top (required)>'
        from /usr/local/bundle/bin/sitediff:25:in `load'
        from /usr/local/bundle/bin/sitediff:25:in `<main>'
root@f80772921e74:/project#
```

Used image: https://hub.docker.com/layers/evolvingweb/sitediff/latest/images/sha256-a2529b4a26e58d5c1288372d832e90094b96096ef870702dd5e40c2e5cf572bf?context=explore

Do you need the configuration / contents of the mounted folder?

**Comment by kreediam** [comment]
Me too. I don't know ruby at all, but I changed ";" to "=" [here](https://github.com/evolvingweb/sitediff/blob/master/lib/sitediff/fetch.rb#L18) and ran the last two lines from the docker file. That seemed to work for my simple case.

```
gem build sitediff.gemspec && gem install sitediff --no-document
bundle install
```

**Comment by kirk-brown-ew** [comment]
This issue has now been fixed.
