### ISSUE TITLE
Invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by rsynnest** [evolvingweb/sitediff#38]
I'm running a build on commit 70869f7a530 of `dev` branch, and am getting the following error while processing a page during my `sitediff diff`:

```
Traceback (most recent call last):
	33: from /usr/bin/sitediff:23:in `<main>'
	32: from /usr/bin/sitediff:23:in `load'
	31: from /usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/bin/sitediff:9:in `<top (required)>'
	30: from /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	29: from /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	28: from /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	27: from /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	26: from /usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/lib/sitediff/cli.rb:110:in `diff'
	25: from /usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/lib/sitediff.rb:120:in `run'
	24: from /usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/lib/sitediff/fetch.rb:26:in `run'
	23: from /usr/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/hydra/memoizable.rb:51:in `run'
	22: from /usr/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/hydra/runnable.rb:15:in `run'
	21: from /usr/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/multi/operations.rb:43:in `perform'
	20: from /usr/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/multi/operations.rb:164:in `run'
	19: from /usr/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/multi/operations.rb:151:in `check'
	18: from /usr/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/easy/response_callbacks.rb:68:in `complete'
	17: from /usr/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/easy/response_callbacks.rb:68:in `each'
	16: from /usr/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/easy/response_callbacks.rb:68:in `block in complete'
	15: from /usr/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/easy_factory.rb:164:in `block in set_callback'
	14: from /usr/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/operations.rb:35:in `finish'
	13: from /usr/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/callbacks.rb:145:in `execute_callbacks'
	12: from /usr/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/callbacks.rb:145:in `each'
	11: from /usr/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/callbacks.rb:146:in `block in execute_callbacks'
	10: from /usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/lib/sitediff/uriwrapper.rb:107:in `block in typhoeus_request'
	 9: from /usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/lib/sitediff/fetch.rb:48:in `block (2 levels) in queue_path'
	 8: from /usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/lib/sitediff/fetch.rb:58:in `process_results'
	 7: from /usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/lib/sitediff.rb:90:in `process_results'
	 6: from /usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/lib/sitediff.rb:78:in `sanitize'
	 5: from /usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/lib/sitediff.rb:78:in `map'
	 4: from /usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/lib/sitediff.rb:81:in `block in sanitize'
	 3: from /usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/lib/sitediff/sanitize.rb:35:in `sanitize'
	 2: from /usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/lib/sitediff/sanitize.rb:97:in `regexps'
	 1: from /usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/lib/sitediff/sanitize.rb:148:in `prettify'
/usr/lib/ruby/gems/2.5.0/gems/sitediff-0.0.4/lib/sitediff/sanitize.rb:148:in `sub!': invalid byte sequence in UTF-8 (ArgumentError)
```

I was able to fix this error with no noticeable detrimental effects to the diff report by adding the following line. The addition encodes the string to UTF-8 before sanitizing, replacing any invalid or undefined bytes with an empty string:

``` diff
# Remove xml declaration and <html> tags
+ str = str.encode('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '')
str.sub!(/\A<\?xml.*$\n/, '')
str.sub!(/\A^<html>$\n/, '')
str.sub!(%r{</html>\n\Z}, '')     
```

I'm not sure if this is a proper fix, not a Ruby dev, and not sure where to PR to, so just submitting this fix as an issue in case its useful.

**Comment by zl2** [comment]
Thanks for you report and suggested solution! I was just looking at UTF-8 errors throughout.

Your suggested fix indeed works for that case (UTF-8 errors also appear elsewhere).

I'll note for myself and my team here that replacing them with the unicode undefined character "\xff\xfd" (which would have been a more informative fix) gives a different error.

    str = str.encode('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: "\xff\xfd")

Thanks again.

**Comment by zl2** [comment]
We've pushed a fix similar to the one suggested here to the latest `dev` branch. I've tested it against a previously known UTF-8 erorr. Please feel free to reopen if the error occurs again.
