### ISSUE TITLE
error reading config file in `sitediff serve`

### ISSUE THREAD

**Issue by slefevre-highlights** [evolvingweb/sitediff#9]
I have a sitediff that I initialized. I can do `sitediff diff`, and get results, but the `serve` command crashes. 
```
~/sitediffs/www.mysite.com$ sitediff serve
[sitediff] Reading config file: /home/user/sitediffs/www.mysite.com/sitediff/sitediff.yaml
/usr/lib/ruby/2.1.0/psych.rb:464:in `initialize': No such file or directory @ rb_sysopen - output/settings.yaml (Errno::ENOENT)
	from /usr/lib/ruby/2.1.0/psych.rb:464:in `open'
	from /usr/lib/ruby/2.1.0/psych.rb:464:in `load_file'
	from /var/lib/gems/2.1.0/gems/sitediff-0.0.3/lib/sitediff/webserver/resultserver.rb:56:in `initialize'
	from /var/lib/gems/2.1.0/gems/sitediff-0.0.3/lib/sitediff/cli.rb:131:in `new'
	from /var/lib/gems/2.1.0/gems/sitediff-0.0.3/lib/sitediff/cli.rb:131:in `serve'
	from /var/lib/gems/2.1.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.1.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.1.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /var/lib/gems/2.1.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /var/lib/gems/2.1.0/gems/sitediff-0.0.3/bin/sitediff:10:in `<top (required)>'
	from /usr/local/bin/sitediff:23:in `load'
	from /usr/local/bin/sitediff:23:in `<main>'

$  ruby -v
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

```
I tried to get the version from sitediff, but it didn't recognize `-v` or `--version`. I installed it ~ two days ago.

**Comment by slefevre-highlights** [comment]
Also, here is the `sitediff diff` command running okay
```~/sitediffs/www.mysite.com$ sitediff diff
[sitediff] Reading config file: /home/user/sitediffs/www.mysite.com/sitediff/sitediff.yaml
[sitediff] Using sites from cache: before
...
```
Also I'm running Debian 8.7 (Jessie)

**Comment by shahinam** [comment]
@slefevre-highlights  Yes, I was able to reproduce this.

This happens if `sitediff serve` is run before `sitediff diff` - as the later creates the output folder with diff and the configuration file `settings.yml`

I have created a PR to output a message that you need to run `diff` before running `serve`.
